name: deprem_yeni
description: Deprem Uyarı Sistemi
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  geolocator: ^13.0.2
  flutter_tts: ^4.2.2  
  intl: ^0.20.2  
  shared_preferences: ^2.2.2
  



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/earthquake_loading.json

dependency_overrides:
  flutter_blue:
    git:
      url: https://github.com/esra2406/flutter_blue.git
      ref: master

